name: Code QA checks
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    branches:
      - 'main'
jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
          architecture: x64
          prerelease: true
          enable-pep582: true
          cache: true
      - name: Install local
        run: pdm install
      - name: Run linting
        run: pdm lint
      - name: Run testing
        run: pdm test
