name: Release PyPI Version

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.9
          architecture: x64
          prerelease: true
          enable-pep582: true
          cache: true
      - name: Run build
        run: pdm build
      - name: Publish version
        run: pdm publish --username __token__ --password ${{secrets.PYPI_TOKEN}}
      - name: Create Release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.REVISION }}
          release_name: ${{ github.ref }}
          body_path: .changelog.md
          draft: false
          prerelease: false
