name: Release version

on:
  push:
    tags:
      - "*.*.*"
permissions:
  contents: write
jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.9
          architecture: x64
          prerelease: true
          enable-pep582: true
          cache: true
      - name: Run build
        run: pdm build
      - name: Publish version
        run: pdm publish --username __token__ --password ${{secrets.PYPI_TOKEN}}
      - name: Create Release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.REVISION }}
          release_name: ${{ github.ref }}
          body_path: .changelog.md
          draft: false
          prerelease: false
  release-github:
    name: release-github
    runs-on: ubuntu-latest
    steps:
      - name: Release Github
        uses: softprops/action-gh-release@v1
        with:
          release_name: "Release ${{${{ github.ref }}}}"
          body_path: "body.md"
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
