name: Upload Python Package
on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

permissions:
  contents: read
jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest

    steps:
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: [3.7, 3.8, 3.9, "3.10", "3.11"] 
          architecture: x64    
          prerelease: true    
          enable-pep582: true
          cache: true
      - name: Run build
        run: pdm build
      - name: Test Build
        run: |
          python3 -m venv fresh_env
          . fresh_env/bin/activate
          pip install dist/*.whl
          dbtv-gen --help
      - name: Publish version
        run: pdm publish --username __token__ --password ${{secrets.PYPI_TOKEN}}
      - name: Create Release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ github.ref }}
          body_path: .changelog.md
          draft: false
          prerelease: false